#! /bin/bash
./Prepare
echo "Building linux"
flutter build linux
echo "Building web"
flutter build web
cd build/web/
cp -a ../../tools/InstallWebsite.sh .
tar czf ../../tools/website.tgz .
cd ../..
ls -ld tools/website.tgz

